### ISSUE TITLE
Add Next Link support

### ISSUE THREAD

**Issue by jithinsankar** [tulupinc/flowbite-next-starter#49]
Is your feature request related to a problem? Please describe.
Browser refreshes on clicking Navbar.Link. 

Describe the solution you'd like
Add Next Link support

**Comment by tulup-conner** [comment]
You should be able to use as={NavLink} to cast the SidebarItem to that. 

Regardless, this is outside the scope of the starter right now since we only have one page, and I don't really plan to add more.
