### ISSUE TITLE
Sidebar component must be rendered on client

### ISSUE THREAD

**Issue by nairanvac** [tulupinc/flowbite-next-starter#50]
Hello, 

I noticed that any pages that use the Sidebar component have to use `"use client"`.  I was hoping to use the Sidebar in my default layout for every page.  Does this mean that none of my pages can be rendered server-side?

Pardon me if this isn't an issue (or isn't specific to this repo).

**Comment by tulup-conner** [comment]
Anything using React client-side features like Context won't work in the server anymore. This is a React design decision; not mine.
