### ISSUE TITLE
Sidebar / Main does grow and shrink with content

### ISSUE THREAD

**Issue by TerminalFi** [tulupinc/flowbite-next-starter#51]
https://github.com/tulupinc/flowbite-next-starter/assets/32599364/329d2f39-b289-4c31-8930-64609f104542

**Comment by tulup-conner** [comment]
Hey there, thanks for pointing this out - it would be cool to fix, but the purpose of this repo is just to demonstrate the code required to render Flowbite React components in Next.js. The actual design isn't important, as long as the components are there :)
