### ISSUE TITLE
Support upgrade to Nextjs 14.x 

### ISSUE THREAD

**Issue by vdwalia** [tulupinc/flowbite-next-starter#53]
It would be big help, if we all work on same page and what's the point of working on older version, if newer version can solve many older problems.

Thank you and i would love to contribute in any way i can. Please do let me know, how can we boost this repo, because it's really really important to all front-end devs.

**Comment by whoafridi** [comment]
@vdwalia i think this repo isnot maintaned right now. You can create a boilerplate so that we also can use yours'

**Comment by tulup-conner** [comment]
Thank you, and yes, you are correct that we should make this upgrade! If someone has the time to put it together, it would be much appreciated.

Also, in the meantime, you can refer to the flowbite-react repo itself as a Next.js 14 starter. It deploys the `app` folder to https://flowbite-react.com, which currently runs Next.js 14.

**Comment by tulup-conner** [comment]
Never mind, I did it myself! :)
