### ISSUE TITLE
Style is blocked when used strict CSP

### ISSUE THREAD

**Issue by Michael-Grupp** [tulupinc/flowbite-next-starter#55]
When I add flowbite react to my nextjs project [with strict CSP](https://github.com/vercel/next.js/tree/canary/examples/with-strict-csp) the styles, that are automatically inserted into the head part are blocked.  

`Refused to apply inline style because it violates the following Content Security Policy directive: "style-src-elem 'self' 'nonce-YjE2ZDgxOWEtNzNmNi00NzQ1LTljZWMtNGM5MTU3YjExMDFk'". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution.`

```html
<style type="text/css">.indiana-scroll-container {
  overflow: auto; }
  .indiana-scroll-container--dragging {
    scroll-behavior: auto !important; }
    .indiana-scroll-container--dragging > * {
      pointer-events: none;
      cursor: -webkit-grab;
      cursor: grab; }
  .indiana-scroll-container--hide-scrollbars {
    overflow: hidden;
    overflow: -moz-scrollbars-none;
    -ms-overflow-style: none;
    scrollbar-width: none; }
    .indiana-scroll-container--hide-scrollbars::-webkit-scrollbar {
      display: none !important;
      height: 0 !important;
      width: 0 !important;
      background: transparent !important;
      -webkit-appearance: none !important; }
  .indiana-scroll-container--native-scroll {
    overflow: auto; }

.indiana-dragging {
  cursor: -webkit-grab;
  cursor: grab; }
</style>
```

It seems this is coming from the dependency `react-indiana-drag-scroll/dist`.   
Is there a way to add the `nonce` which is generated in the nextjs middleware to the `style` tag?  
The nonce I could get like:  
```ts
const nonce = headers().get('x-nonce')
```

**Comment by tulup-conner** [comment]
Hi there, this isn't really in the scope of either the Flowbite React project or this Next.js starter. You'll probably want to try to figure it out on your own, or refer to the maintainers of this dependency.
